book_collector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),

    path('about/', views.about, name='about'),

    path('books/', views.books_index, name='index'),

    path('teas/', views.teas_index, name='index'),

    path('books/<int:book_id>', views.books_detail, name='book_detail'),

    path('teas/<int:tea_id>', views.teas_detail, name='tea_detail'),

    path('books/create/', views.BookCreate.as_view(), name='books_create'),

    path('books/<int:pk>/update/', views.BookUpdate.as_view(), name='books_update'),

    path('books/<int:pk>/delete/', views.BookDelete.as_view(), name='books_delete'),

    path('books/<int:book_id>/add_reading/', views.add_reading, name='add_reading'),

    path('books/<int:book_id>/assoc_tea/<int:tea_id>/', views.assoc_tea, name='assoc_tea'),

    path('books/<int:book_id>/assoc_tea/<int:tea_id>/remove/', views.remove_tea, name='remove_tea'),

    path('teas/create/', views.TeaCreate.as_view(), name='teas_create'),

    path('teas/<int:pk>/update/', views.TeaUpdate.as_view(), name='teas_update'),

    path('teas/<int:pk>/delete/', views.TeaDelete.as_view(), name='teas_delete'),

    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Tea(models.Model):  
    brand = models.CharField(max_length=100)
    flavor = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    rating = models.IntegerField()
    objects = models.Manager()
    
    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        return reverse('tea_detail', kwargs={'tea_id': self.id})

class Book(models.Model):  
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    rating = models.IntegerField()
    teas = models.ManyToManyField(Tea)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        return reverse('book_detail', kwargs={'book_id': self.id})

class Reading(models.Model):
    date = models.DateField('reading date')
    page = models.CharField(max_length=10)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)

    def __str__(self):
        return str(f"{self.page} on {self.date}")

    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Reading

class ReadingForm(ModelForm):
  class Meta:
    model = Reading
    fields = ['date', 'page']

main_app/views.py
# Create your views here.
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Book
from .models import Tea
from .forms import ReadingForm

# Create your views here.
def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html') 

@login_required
def books_index(request):
  books = Book.objects.filter(user=request.user)
  return render(request, 'books/index.html', {'books':books})

@login_required
def teas_index(request):
  teas = Tea.objects.all()
  return render(request, 'teas/index.html', {'teas':teas})

@login_required
def books_detail(request, book_id):
  book = Book.objects.get(id=book_id)
  id_list = book.teas.all().values_list('id')
  available_teas = Tea.objects.exclude(id__in=id_list)
  reading_form = ReadingForm()
  return render(request, 'books/detail.html', {'book':book, 'reading_form':reading_form, 'teas':available_teas})

@login_required
def add_reading(request, book_id):
  form=ReadingForm(request.POST)
  if form.is_valid():
    new_reading=form.save(commit=False)
    new_reading.book_id = book_id
    new_reading.save()
  return redirect('book_detail', book_id = book_id)

@login_required
def assoc_tea(request, book_id, tea_id):
  Book.objects.get(id=book_id).teas.add(tea_id)
  return redirect('book_detail', book_id=book_id)

@login_required
def remove_tea(request, book_id, tea_id):
  Book.objects.get(id=book_id).teas.remove(tea_id)
  return redirect('book_detail', book_id=book_id)

class BookCreate(LoginRequiredMixin, CreateView):
  model = Book
  fields = ['title', 'author', 'description', 'rating']
  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)

class BookUpdate(LoginRequiredMixin, UpdateView):
  model = Book
  fields = ['description', 'rating']
  success_url= '/books/'

class BookDelete(LoginRequiredMixin, DeleteView):
  model = Book
  success_url = '/books/'

@login_required
def teas_detail(request, tea_id):
  tea = Tea.objects.get(id=tea_id)
  return render(request, 'teas/detail.html', {'tea':tea})

class TeaCreate(LoginRequiredMixin, CreateView):
  model = Tea
  fields = '__all__'
  success_url= '/teas/'

class TeaUpdate(LoginRequiredMixin, UpdateView):
  model = Tea
  fields = '__all__'
  success_url= '/teas/'

class TeaDelete(LoginRequiredMixin, DeleteView):
  model = Tea
  success_url = '/teas/'  

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('home')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}
    <h2>About Books and Tea</h2>
    <h4>Any day is better with a good book and a cup of tea!</h4>
    <hr />
    <p>Signup and start keeping track of your favorite books, recent reads, or just make a nice big digital 'TBR' pile (we all have them, don't be shy!). 
        
    <p> Add, remove, update and view the books on your list. Add your own thoughts, or a simple summary of the story you want to save. You can leave a rating as well to show how much you loved it. 
        
    <p>In addition to books, add favorite tea brands and blends, and leave a note about it for everyone else.</p>

    <p>We all have our favorites, but sometimes you want make a note when the pairing was just perfect! Add from the list of teas added by yourself and other users to your books so you know just what to brew up the next time.</p>

    <p>Welcome to your personal library! Come in, sit down and relax with a book and a nice cup of tea.</p>
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Books & Tea</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Nanum+Brush+Script&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper brown">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;Books & Tea</a></li>
        </ul>
        <ul class="right">
          <li><a href="/about">About</a></li>
          {% if user.is_authenticated %}
            <li><a href="{% url 'books_create' %}">Add Book</a></li>
            <li><a href="{% url 'teas_create' %}">Add Tea</a></li>
            <li><a href="/books">Book Library</a></li>
            <li><a href="/teas">Tea Library</a></li>
            <li><a href="{% url 'logout' %}">Log Out</a></li>
          {% else %}
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
            <li><a href="{% url 'login' %}">Log In</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer brown">
    <div class="right">All Rights Reserved, &copy; 2022 Books & Tea &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/books/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Book Details</h1>

<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{book.title}}</span>
                <p>Author: {{book.author}}</p>
                <p>Description: {{book.description}}</p>
                <p>Rating: {{book.rating}}</p>
            </div>
            <div class="card-action">
                <a href="{% url 'books_update' book.id %}">Edit</a>
                <a href="{% url 'books_delete' book.id %}">Delete</a>
            </div>
        </div>
    </div>
<div class="col s6">
    <form action="{% url 'add_reading' book.id %}" method="POST">
        {% csrf_token %}
        {{ reading_form.as_p }}
        <input type="submit" class="btn" value="Add Reading">
      </form>
    <table class="striped">
        <p>Reading Progress:</p>
        <thead>
        <tr><th>Date:</th><th>Page:</th></tr>
        </thead>
        <tbody>
        {% for reading in book.reading_set.all %}
            <tr>
            <td>{{reading.date}}</td>
            <td>{{reading.page}}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
</div>
<hr>
<div class="row">
  <div class="col s6">
    <h3>Tea Blends to have with: {{ book.title }}</h3>
    {% if book.teas.count %}
      {% for tea in book.teas.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              <span>{{ tea.flavor }}</span> by {{ tea.brand }} goes well with this book.
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'remove_tea' book.id tea.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Remove</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Teas Yet :(</h5>
    {% endif %}
  </div>
  <div class="col s6">
    <h3>Available Teas</h3>
    {% if teas.count %}
      {% for tea in teas.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              <span>{{ tea.flavor }}</span> by {{ tea.brand }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_tea' book.id tea.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No more tea blends available.</h5>
    {% endif %}
  </div>
</div>
<script>
    const dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
      format: 'yyyy-mm-dd',
      defaultDate: new Date(),
      setDefaultDate: true,
      autoClose: true
    });
  </script>
{% endblock %}

main_app/templates/books/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Book List</h1>

{% for book in books %}
  <div class="card">
    <a href="{% url 'book_detail' book.id %}">
      <div class="card-content">
        <span class="card-title">{{book.title}}</span>
        <h5>Author: {{book.author}}</h5>
        <p>Rating: {{book.rating}} </p>
      </div>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Welcome to Books and Tea!</h1>
<img class='image' src="https://i.imgur.com/Qw8gCVo.png" title="source: imgur.com" />

{% endblock %}

main_app/templates/main_app/book_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Book</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{object.title}}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' book.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/book_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
  <h1>Edit Book<span class="teal-text">{{ object.name }}</span></h1>
{% else %}
  <h1>Add A Book</h1>
{% endif %}


<form action="" method="POST">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn">
</form>
<div class='form-img'>
  <img src="https://i.imgur.com/z4FGNRJ.png" title="source: imgur.com" />
</div>
{% endblock %}

main_app/templates/main_app/tea_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Tea</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{object.name}}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'tea_detail' tea.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/tea_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
  <h1>Edit Tea<span class="teal-text">{{ object.name }}</span></h1>
{% else %}
  <h1>Add Tea</h1>
{% endif %}


<form action="" method="POST">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn">
</form>
<div class='form-img'>
  <img src="https://i.imgur.com/irSoocS.png" title="source: imgur.com" />
</div>
{% endblock %}

main_app/templates/teas/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Tea Details</h1>

<div class="row">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{tea.brand}}</span>
                <p>Flavor: {{tea.flavor}}</p>
                <p>Description: {{tea.description}}</p>
                <p>Rating: {{tea.rating}}</p>
            </div>
            <div class="card-action">
                <a href="{% url 'teas_update' tea.id %}">Edit</a>
                <a href="{% url 'teas_delete' tea.id %}">Delete</a>
            </div>
        </div>
    </div>
{% endblock %}

main_app/templates/teas/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Tea List</h1>

{% for tea in teas %}
  <div class="card">
    <a href="{% url 'tea_detail' tea.id %}">
      <div class="card-content">
        <span class="card-title">{{tea.flavor}}</span>
        <h5>Brand: {{tea.brand}}</h5>
        <p>Rating: {{tea.rating}} </p>
      </div>
  </div>
{% endfor %}

{% endblock %}